apiVersion: v1
kind: Service
metadata:
  labels:
    app: spo-backend
  name: spo-backend-service-dev
  namespace: spo
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8000
  selector:
    app: spo-backend
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: spo-backend
  name: spo-backend-dev
  namespace: spo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spo-backend
  template:
    metadata:
      labels:
        app: spo-backend
    spec:
      containers:
      - envFrom:
        - secretRef:
            name: spo-backend-secret
        image: arigatopix/spo-backend:v1.0.0-8
        imagePullPolicy: Always
        name: primary
        ports:
        - containerPort: 80
          name: api-port
          protocol: TCP
        resources:
          limits:
            cpu: 1
            memory: 1024Mi
          requests:
            cpu: 0.5
            memory: 512Mi
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: 50m
  labels:
    app: spo-backend
  name: spo-backend-ing-dev
  namespace: spo
spec:
  ingressClassName: nginx
  rules:
  - host: spo-api.pea.co.th
    http:
      paths:
      - backend:
          service:
            name: spo-backend-service-dev
            port:
              number: 80
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - spo-api.pea.co.th
