domain: n2app-log.pea.co.th

loki-stack:
  enabled: true
  test_pod:
    enabled: false
  promtail:
    fullnameOverride: promtail
    config:
      clients:
        - url: http://loki-log:3100/loki/api/v1/push
  loki:
    fullnameOverride: loki-log
    persistence:
      enabled: true
    config:
    alerting_groups: []

  grafana:
    enabled: true
    fullnameOverride: loki-log-grafana
    envRenderSecret: {}
    admin:
      existingSecret: "grafana-credentials"
      userKey: GRAFANA_USER
      passwordKey: GRAFANA_PASSWORD
    image:
      tag: 11.1.0
    grafana.ini:
      server:
        root_url: https://n2app-log.pea.co.th
        domain: n2app-log.pea.co.th
