apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: n2app-frontend
spec:
  generators:
    - clusters:
        selector:
          matchLabels:
            custom: "true"
  template:
    metadata:
      name: "n2app-frontend-{{name}}"
    spec:
      project: "default"
      source:
        repoURL: https://github.com/arigatopix/n2app-argocd.git
        targetRevision: "{{name}}" #Based on environment
        path: "manifests/n2app-frontend"
      destination:
        name: in-cluster
        namespace: n2app-frontend
      syncPolicy:
        automated:
          selfHeal: false
          prune: true
        syncOptions:
          - CreateNamespace=true
