apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: grafana-credentials
  namespace: monitoring
  labels:
    argocd.argoproj.io/instance: monitoring
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: k8s-secret-store
  target:
    name: grafana-credentials
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: GRAFANA_USER
      remoteRef:
        key: initial-secret
        property: GRAFANA_USER
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: GRAFANA_PASSWORD
      remoteRef:
        key: initial-secret
        property: GRAFANA_PASSWORD
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
  dataFrom:
    - extract:
        key: initial-secret
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
