apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: k8s-secret-store
spec:
  provider:
    kubernetes:
      auth:
        serviceAccount:
          name: ext-secret-sa
          namespace: default
      remoteNamespace: "{{ .ExternalSecret.Namespace }}"
      server:
        caProvider:
          key: ca.crt
          name: kube-root-ca.crt
          namespace: default
          type: ConfigMap
        url: https://kubernetes.default
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: n2app-backend-credentials
  namespace: n2app-backend
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: k8s-secret-store
  target:
    name: n2app-backend-credentials
  dataFrom:
    - extract:
        key: n2app-backend-secret
