apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: n2app-secret-store
  namespace: n2app
spec:
  provider:
    kubernetes:
      remoteNamespace: n2app
      server:
        url: https://kubernetes.default.svc
        caProvider:
          type: ConfigMap
          name: kube-root-ca.crt
          key: ca.crt
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: n2app-backend-credentials
  namespace: n2app-backend
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: SecretStore
    name: n2app-secret-store
  target:
    name: n2app-backend-credentials
  dataFrom:
    - extract:
        key: n2app-backend-secret
