apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-argocd-deployment
  labels:
    app: hello-argocd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-argocd
  template:
    metadata:
      labels:
        app: hello-argocd
    spec:
      containers:
      - name: hello-argocd
        image: crccheck/hello-world:latest
        ports:
        - containerPort: 8000
