apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-hello-argocd
spec:
  ingressClassName: nginx
  rules:
  - host: "n2app.pea.co.th"
    http:
      paths:
      - pathType: Prefix
        path: "/hello-argocd"
        backend:
          service:
            name: hello-argocd-service
            port:
              number: 80
