domain: n2app-matric.pea.co.th
domain1: alm.pea.co.th
domain2: prom.pea.co.th

environment: production

kube-prometheus-stack:
  grafana:
    ingress:
      enabled: true
      ingressClassName: nginx
      hosts:
        - n2app-matric.pea.co.th
      tls:
        - secretName: grafana-k8s-cert
          hosts:
            - n2app-matric.pea.co.th
    grafana.ini:
      server:
        root_url: https://n2app-matric.pea.co.th
        domain: n2app-matric.pea.co.th

  # Add cert-manager configuration if you're using it
  certManager:
    enabled: true
    certificate:
      create: true
      dnsNames:
        - n2app-matric.pea.co.th
