domain: n2app-matric.pea.co.th
domain1: alm.pea.co.th
domain2: prom.pea.co.th

environment: production

kube-prometheus-stack:
  enabled: true
  fullnameOverride: prometheus

  prometheus-node-exporter:
    hostRootFsMount:
      enabled: false

  grafana:
    admin:
      existingSecret: "grafana-credentials"
      userKey: GRAFANA_USER
      passwordKey: GRAFANA_PASSWORD
    grafana.ini:
      server:
        root_url: https://n2app-matric.pea.co.th
        domain: n2app-matric.pea.co.th

  alertmanager:
    alertmanagerSpec:
      alertmanagerConfigMatcherStrategy:
        type: None
