apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-hello-domain
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  tls:
    - hosts:
        - n2solar.pea.co.th
      secretName: tls-secret
  ingressClassName: nginx
  rules:
    - host: n2solar.pea.co.th
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: hello-domain-service
                port:
                  number: 80
