resources:
  - ../../base

images:
  - name: arigatopix/n2app-frontend
    newTag: v1.0.0-26

commonLabels:
  app: n2app

patches:
  - path: patch.yaml
    target:
      kind: Deployment
      name: n2app
  - path: ingress-patch.yaml
    target:
      kind: Ingress
      name: n2app
      namespace: n2app-frontend
  - target:
      kind: Ingress
      name: n2app
      namespace: n2app-frontend
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: n2app.pea.co.th
