resources:
  - ../../base
images:
  - name: arigatopix/n2app-backend
    newTag: v1.0.0-5
commonLabels:
  app: n2app
patches:
  - path: patch.yaml
    target:
      kind: Deployment
      name: n2app
  - path: ingress-patch.yaml
    target:
      kind: Ingress
      name: n2app
      namespace: n2app-backend
  # - path: secret-patch.yaml
  #   target:
  #     kind: ExternalSecret
  #     name: n2app
  #     namespace: n2app-backend
  - target:
      kind: Ingress
      name: n2app
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: n2app-api.pea.co.th
