# apiVersion: external-secrets.io/v1beta1
# kind: SecretStore
# metadata:
#   name: n2app-backend-secret-store
#   namespace: n2app-backend
# spec:
#   provider:
#     kubernetes:
#       server:
#         url: https://kubernetes.default.svc
#         caProvider:
#           type: ConfigMap
#           name: kube-root-ca.crt
#           key: ca.crt
#       remoteNamespace: n2app-backend
#       auth:
#         serviceAccount:
#           name: default # Or specify a custom ServiceAccount if you've created one
# ---
# apiVersion: external-secrets.io/v1beta1
# kind: ExternalSecret
# metadata:
#   name: n2app-backend-credentials
#   namespace: n2app-backend
# spec:
#   refreshInterval: 1m
#   secretStoreRef:
#     kind: SecretStore
#     name: n2app-backend-secret-store
#   target:
#     name: n2app-backend-credentials
#   dataFrom:
#     - extract:
#         key: n2app-backend-secret
