apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: n2app-backend-credentials
  namespace: n2app-backend
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: SecretStore
    name: n2app-backend-secret-store
  target:
    name: n2app-backend-credentials
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: n2app-backend-secret
