apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: n2app-backend-credentials
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: k8s-secret-store
  target:
    name: n2app-backend-credentials
    creationPolicy: Owner
    deletionPolicy: Retain
  dataFrom:
    - key: initial-secret
