apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: grafana-credentials
  namespace: monitoring
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: k8s-secret-store
  target:
    name: grafana-credentials
    creationPolicy: Owner
  data:
    - secretKey: GRAFANA_USER
      remoteRef:
        key: initial-secret
        property: GRAFANA_USER
    - secretKey: GRAFANA_PASSWORD
      remoteRef:
        key: initial-secret
        property: GRAFANA_PASSWORD
  dataFrom:
    - extract:
        key: initial-secret
