# apiVersion: cert-manager.io/v1
# kind: Certificate
# metadata:
#   name: grafana-k8s-cert
# spec:
#   secretName: grafana-k8s-cert
#   dnsNames:
#     - n2app-matric.pea.co.th
#   issuerRef:
#     name: lets-encrypt-issuer-prod
#     kind: ClusterIssuer
#     group: cert-manager.io
