apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: spo-backend-ing
spec:
  rules:
    - host: api-spo-dev.pea.co.th
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: spo-backend-service
                port:
                  number: 80
  tls:
    - hosts:
        - api-spo-dev.pea.co.th
