resources:
  - ../../base
images:
  - name: arigatopix/spo-backend
    newTag: sit-dev-52
commonLabels:
  app: spo-backend
namespace: spo-backend
nameSuffix: -dev
patches:
  - path: patch.yaml
    target:
      kind: Deployment
      name: spo-backend
  - path: ingress-patch.yaml
    target:
      kind: Ingress
      name: spo-backend-ing
      namespace: spo
