apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: longhorn-ing
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: HTTP
spec:
  ingressClassName: nginx
  rules:
    - host: n2app-longhorn.pea.co.th
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: longhorn-frontend
                port:
                  number: 80
